apiVersion: v1
kind: Pod
metadata:
  name: helloserver
  namespace: default
  labels:
    app: hello
    name: helloserver
spec:
  containers:
  - name: helloserver
    image: lily123/helloserver:latest
    ports:
    - containerPort: 10000
  restartPolicy: Never